# Generated by Django 3.2 on 2021-04-26 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0002_alter_knowledgecategory_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Author's full name.")),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Book Id')),
                ('name', models.CharField(max_length=255, verbose_name="Book's name")),
                ('publish_date', models.PositiveSmallIntegerField(verbose_name='Year of publishing')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book_shop.author', verbose_name='Authors')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book_shop.knowledgecategory', verbose_name='Category Id')),
            ],
        ),
    ]
