# Generated by Django 3.2 on 2021-04-26 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0003_author_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_count', models.PositiveIntegerField(verbose_name='Outcome count')),
                ('out_date', models.DateField(verbose_name='Outcome date')),
                ('out_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Outcome price')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book_shop.book', verbose_name='Book')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book_shop.knowledgecategory', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='BookIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_count', models.PositiveIntegerField(verbose_name='Income count')),
                ('in_date', models.DateField(verbose_name='Income date')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book_shop.book', verbose_name='Book')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book_shop.knowledgecategory', verbose_name='Category')),
            ],
        ),
    ]
