# Generated by Django 3.2 on 2021-05-03 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0004_bookincome_bookoutcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookincome',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book_shop.knowledgecategory', verbose_name='Category'),
        ),
    ]
