# Generated by Django 3.2 on 2021-05-03 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0005_alter_bookincome_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookincome',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book_shop.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='bookoutcome',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book_shop.book', verbose_name='Book'),
        ),
    ]
